# Multiclass Classification using Keras
This notebook demonstrates a step-by-step implementation of a multiclass classification model using TensorFlow's Keras API. The dataset used is the Iris dataset, which is a classic machine learning dataset for classification.

## Step 1: Load and Preprocess the Data
We load the Iris dataset, split it into training and test sets, standardize the features, and one-hot encode the target labels for use in a neural network.

In [1]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

# Load the Iris dataset
iris = pd.read_csv('iris_dataset.csv')
X = np.array(iris.iloc[:,:-1])
y = np.array(iris.iloc[:,-1])

print(f"{'Data':<20} {'Label'}")
for i in range(10):
    print(f'{str(X[i]):<20} {y[i]}')


Data                 Label
[5.1 3.5 1.4 0.2]    0
[4.9 3.  1.4 0.2]    0
[4.7 3.2 1.3 0.2]    0
[4.6 3.1 1.5 0.2]    0
[5.  3.6 1.4 0.2]    0
[5.4 3.9 1.7 0.4]    0
[4.6 3.4 1.4 0.3]    0
[5.  3.4 1.5 0.2]    0
[4.4 2.9 1.4 0.2]    0
[4.9 3.1 1.5 0.1]    0


In [2]:
# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the feature data (mean=0, variance=1)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f"{'Data':<50} {'Label'}")
for i in range(10):
    print(f'{str(X_train[i]):<50} {y_train[i]}')

Data                                               Label
[-1.47393679  1.20365799 -1.56253475 -1.31260282]  0
[-0.13307079  2.99237573 -1.27600637 -1.04563275]  0
[1.08589829 0.08570939 0.38585821 0.28921757]      1
[-1.23014297  0.75647855 -1.2187007  -1.31260282]  0
[-1.7177306   0.30929911 -1.39061772 -1.31260282]  0
[ 0.59831066 -1.25582892  0.72969227  0.95664273]  2
[0.72020757 0.30929911 0.44316389 0.4227026 ]      1
[-0.74255534  0.98006827 -1.27600637 -1.31260282]  0
[-0.98634915  1.20365799 -1.33331205 -1.31260282]  0
[-0.74255534  2.32160658 -1.27600637 -1.44608785]  0


In [3]:
# One-hot encode the labels
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)

print(f"{'Data':<50} {'Label'}")
for i in range(10):
    print(f'{str(X_train[i]):<50} {y_train[i]}')

Data                                               Label
[-1.47393679  1.20365799 -1.56253475 -1.31260282]  [1. 0. 0.]
[-0.13307079  2.99237573 -1.27600637 -1.04563275]  [1. 0. 0.]
[1.08589829 0.08570939 0.38585821 0.28921757]      [0. 1. 0.]
[-1.23014297  0.75647855 -1.2187007  -1.31260282]  [1. 0. 0.]
[-1.7177306   0.30929911 -1.39061772 -1.31260282]  [1. 0. 0.]
[ 0.59831066 -1.25582892  0.72969227  0.95664273]  [0. 0. 1.]
[0.72020757 0.30929911 0.44316389 0.4227026 ]      [0. 1. 0.]
[-0.74255534  0.98006827 -1.27600637 -1.31260282]  [1. 0. 0.]
[-0.98634915  1.20365799 -1.33331205 -1.31260282]  [1. 0. 0.]
[-0.74255534  2.32160658 -1.27600637 -1.44608785]  [1. 0. 0.]


## Step 2: Build the Model
We define a Sequential neural network model with the following structure:
- Input layer with 64 neurons and ReLU activation
- Hidden layer with 32 neurons and ReLU activation
- Output layer with 3 neurons and softmax activation for multiclass classification.

In [4]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the model
model = Sequential([
    Dense(64, input_shape=(X_train.shape[1],), activation='relu'),  # Input layer with 64 neurons
    Dense(32, activation='relu'),  # Hidden layer with 32 neurons
    Dense(3, activation='softmax')  # Output layer with 3 classes
])


## Step 3: Compile the Model
We compile the model using the Adam optimizer, categorical crossentropy loss, and accuracy as the evaluation metric.

In [5]:

# Compile the model
optimizer = Adam(learning_rate=0.01)
model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=['accuracy'])


## Step 4: Train the Model
We train the model on the training data for 50 epochs, using a batch size of 16 and validating on the test set.

In [6]:

# Train the model
history = model.fit(X_train, y_train, 
                    validation_data=(X_test, y_test), 
                    epochs=50, 
                    batch_size=16)


Epoch 1/50
8/8 [==============================] - 0s 19ms/step - loss: 0.8684 - accuracy: 0.7917 - val_loss: 0.7613 - val_accuracy: 0.8333
Epoch 2/50
8/8 [==============================] - 0s 4ms/step - loss: 0.7546 - accuracy: 0.8000 - val_loss: 0.6523 - val_accuracy: 0.8333
Epoch 3/50
8/8 [==============================] - 0s 4ms/step - loss: 0.6595 - accuracy: 0.8083 - val_loss: 0.5651 - val_accuracy: 0.8333
Epoch 4/50
8/8 [==============================] - 0s 4ms/step - loss: 0.5818 - accuracy: 0.8083 - val_loss: 0.4940 - val_accuracy: 0.8667
Epoch 5/50
8/8 [==============================] - 0s 4ms/step - loss: 0.5199 - accuracy: 0.8083 - val_loss: 0.4390 - val_accuracy: 0.8667
Epoch 6/50
8/8 [==============================] - 0s 4ms/step - loss: 0.4698 - accuracy: 0.8167 - val_loss: 0.3959 - val_accuracy: 0.9000
Epoch 7/50
8/8 [==============================] - 0s 4ms/step - loss: 0.4300 - accuracy: 0.8167 - val_loss: 0.3621 - val_accuracy: 0.9000
Epoch 8/50
8/8 [=================

## Step 5: Evaluate the Model
We evaluate the model on the test set and print the test accuracy.

In [7]:

# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Test accuracy: {test_accuracy:.2f}")


1/1 - 0s - loss: 0.0461 - accuracy: 1.0000 - 16ms/epoch - 16ms/step
Test accuracy: 1.00


## Step 6: Make Predictions
We use the trained model to make predictions for the first 5 samples in the test set.

In [8]:

# Make predictions
predictions = model.predict(X_test[:5])

print('\n Predicted Probabilities:')
print(f"{'Class 0':<10}{'Class 1':<10}{'Class 2':<10}")
for pred_prob in predictions:
    print(f"{pred_prob[0]:<10.3}{pred_prob[1]:<10.3}{pred_prob[2]:<10.3}")

1/1 [==============================] - 0s 58ms/step

 Predicted Probabilities:
Class 0   Class 1   Class 2   
0.000649  0.963     0.0362    
0.994     0.00501   0.000752  
6.82e-11  4.23e-05  1.0       
0.00101   0.842     0.157     
0.000143  0.902     0.0978    


## Step 7: Post-process Predictions
We convert the predicted probabilities into class labels using `np.argmax`, and compare them with the true labels.

In [9]:

# Convert probabilities to class labels
predicted_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(y_test[:5], axis=1)

print('True Label:', true_labels)
print(f"Predicted Classes:")
for pred_class in predicted_labels:
    print(pred_class)

True Label: [1 0 2 1 1]
Predicted Classes:
1
0
2
1
1
